# Generated by Django 2.2.7 on 2019-11-19 00:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pets.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField()),
                ('is_paid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('short_description', models.CharField(max_length=2000)),
                ('text', models.TextField()),
                ('image', models.ImageField(upload_to=pets.models.pet_photos_path, verbose_name='image*')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SSLSetup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_id', models.CharField(max_length=100)),
                ('store_password', models.CharField(max_length=100)),
                ('base_url', models.CharField(max_length=1000)),
                ('validation_api_url', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='SSLPaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=1000, unique=True)),
                ('initial_time', models.DateTimeField()),
                ('session_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('transection_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('val_id', models.CharField(blank=True, max_length=1000, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('PROCESSING', 'PROCESSING'), ('COMPLETED', 'COMPLETED'), ('VALID', 'VALID'), ('FAILED', 'FAILED'), ('CANCELLED', 'CANCELLED')], default='PENDING', max_length=50)),
                ('is_paid', models.BooleanField(default=False)),
                ('tran_date', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('store_amount', models.CharField(blank=True, max_length=50, null=True)),
                ('card_type', models.CharField(blank=True, max_length=50, null=True)),
                ('card_no', models.CharField(blank=True, max_length=500, null=True)),
                ('currency', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=500, null=True)),
                ('card_issuer', models.CharField(blank=True, max_length=100, null=True)),
                ('card_brand', models.CharField(blank=True, max_length=100, null=True)),
                ('card_issuer_country', models.CharField(blank=True, max_length=100, null=True)),
                ('card_issuer_country_code', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_type', models.CharField(blank=True, max_length=100, null=True)),
                ('currency_amount', models.CharField(blank=True, max_length=100, null=True)),
                ('verify_sign', models.CharField(blank=True, max_length=500, null=True)),
                ('verify_key', models.CharField(blank=True, max_length=2000, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=100, null=True)),
                ('risk_title', models.CharField(blank=True, max_length=100, null=True)),
                ('appointment_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ssl_record', to='pets.AppointmentRequest')),
            ],
        ),
        migrations.CreateModel(
            name='PetOwner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=5, verbose_name='Gender*')),
                ('address', models.CharField(max_length=1000)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pet_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('birds', 'Birds'), ('lab', 'Lab animal'), ('O', 'Other')], max_length=25)),
                ('color', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('seven_day_vaccinated', models.BooleanField(default=False)),
                ('forty_five_day_vaccinated', models.BooleanField(default=False)),
                ('yearly_vaccinated', models.BooleanField(default=False)),
                ('profile_photo', models.ImageField(upload_to=pets.models.pet_photos_path)),
                ('first_image', models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photos_path)),
                ('second_image', models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photos_path)),
                ('third_image', models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photos_path)),
                ('forth_image', models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photos_path)),
                ('fifth_image', models.ImageField(blank=True, null=True, upload_to=pets.models.pet_photos_path)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to='pets.PetOwner')),
            ],
        ),
        migrations.AddField(
            model_name='appointmentrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointment_requests', to='pets.Pet'),
        ),
    ]
