# Generated by Django 2.2.7 on 2019-11-20 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sslpaymentrecord',
            name='appointment_request',
        ),
        migrations.DeleteModel(
            name='AppointmentRequest',
        ),
        migrations.DeleteModel(
            name='SSLPaymentRecord',
        ),
    ]
