# Generated by Django 2.2.7 on 2019-12-02 10:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_forumcomment_forumpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumcomment',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='forumcomment',
            name='forum_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='pets.ForumPost'),
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
