# Generated by Django 2.2.7 on 2019-11-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('director', 'Director'), ('pet_owner', 'Pet Owner'), ('receptionist', 'Receptionist'), ('inventory_manager', 'Inventory Manager'), ('dev', 'DEV'), ('accountant', 'Accountant'), ('typist', 'Typist')], max_length=50),
        ),
    ]
